---
- name: master_instance
  hosts: master
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - masternode
  vars:
    ca.pem: /home/keys/ca.pem
    ca_key: /home/keys/ca-key.pem
    remote_key_path: /home/ubuntu
    keys_path: /opt/keys

- name: slave-node
  remote_user: ubuntu
  hosts: slaves
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - slavenodes
  vars:
    ca.pem: /home/keys/ca.pem
    ca_key: /home/keys/ca-key.pem
    remote_key_path: /home/ubuntu
    keys_path: /opt/keys      

   
- name: localhost
  hosts: localhost
  roles:
    - curls

